## Settings
title: jing blog
owner: "zjw"
url: "https://jingwen67.github.io"
baseurl: ""
permalink: /:title/
description: ""
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
email: "jz3093@barnard.edu"
github: "jingwen67/jingwen67.github.io"
# path to: css/, fonts/, img/ and js/
assets_path: "/assets" # i.e. "/assets" 
statement: "intelligent"
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3
# texts randomly displayed in background
bgtext: "happywilliam"